interface Env {
  SUPABASE_URL: string;
  SUPABASE_ANON_KEY: string;
  SUPABASE_SERVICE_ROLE_KEY: string;
  VITE_SUPABASE_URL: string;
  VITE_SUPABASE_ANON_KEY: string;
  WEB3FORMS_ACCESS_KEY?: string;
  FORMSPREE_ENDPOINT?: string;
  VITE_COMPANY_NAME?: string;
}
